gems:
  - jekyll-sitemap
permalink: /blog/:title.html

conferences:
  - year: 2015
    talks:
    - title: PHP Barcelona conference
      location: Barcelona, Spain
      date: 30-31st October
      spoken:
          - title: From PHP to Machine Code
            slides: https://speakerdeck.com/juokaz/from-php-to-machine-code-phpcon-japan-2015
            feedback: https://joind.in/talk/view/15866
    - title: PHP Japan conference
      location: Tokyo, Japan
      date: 3rd October
      spoken:
          - title: From PHP to Machine Code
            slides: https://speakerdeck.com/juokaz/from-php-to-machine-code-phpcon-japan-2015
            feedback: https://joind.in/talk/view/15365
    - title: NYPHP user group
      location: New York, NY, USA
      date: 25th September
      spoken:
          - title: From PHP to Machine Code
            slides: https://speakerdeck.com/juokaz/from-php-to-machine-code-vilnius-php-2015
    - title: Future Insights Live conference
      location: Las Vegas, NV, USA
      date: 2-4th June
      spoken:
          - title: "How To Keep Calm And Ship It"
            slides: https://speakerdeck.com/juokaz/how-to-keep-calm-and-ship-it-future-insights-live-2015
    - title: Kaunas PHP user group
      location: Kaunas, Lithuania
      date: 13th May
      spoken:
          - title: From PHP to Machine Code
            slides: https://speakerdeck.com/juokaz/from-php-to-machine-code-vilnius-php-2015
    - title: Vilnius PHP user group
      location: Vilnius, Lithuania
      date: 7th May
      spoken:
          - title: From PHP to Machine Code
            slides: https://speakerdeck.com/juokaz/from-php-to-machine-code-vilnius-php-2015
  - year: 2014
    talks:
    - title: Build Stuff conference
      location: Vilnius, Lithuania
      date: 19-23th November
      spoken:
          - title: "Making decisions with data"
            slides: https://speakerdeck.com/juokaz/making-decisions-with-data-buildstuff-2014
    - title: True North PHP conference
      location: Toronto, Canada
      date: 6-8th November
      spoken:
          - title: "Building software fast"
            feedback: http://joind.in/talk/view/12706
          - title: "Beyond the PHP mountain"
            feedback: http://joind.in/talk/view/12705
    - title: PHPCon PL conference
      location: Szczyrk, Poland
      date: 26-28th Septemeber
      spoken:
          - title: "Beyond the PHP mountain"
            feedback: http://joind.in/talk/view/11838
    - title: PHP UK conference
      location: London, UK
      date: 21-22th February
      info: Delivered the Opening Keynote to over 700 people
      spoken:
          - title: "What Makes Technology Work"
            slides: http://www.slideshare.net/juokaz/what-makes-technology-work
            feedback: http://joind.in/talk/view/10684
  - year: 2013
    talks:
    - title: Lone Start PHP conference
      location: Dallas, TX, USA
      date: 28-29th June
      spoken:
          - title: "Virtualized Development"
            feedback: http://joind.in/talk/view/8698
            slides: http://www.slideshare.net/juokaz/virtualized-development-lone-star-php
          - title: "You Can't Optimize What You Can't Measure"
            feedback: http://joind.in/talk/view/8697
            slides: http://www.slideshare.net/juokaz/you-cant-optimize-what-you-cannot-measure-lone-star-php
    - title: Web-5 conference
      location: Béziers, France
      date: 14-15th June
      spoken:
          - title: "Process any amount of data. Any time"
            slides: http://www.slideshare.net/juokaz/process-any-amount-of-data-any-time-web5-conference
    - title: Dutch PHP conference
      location: Amsterdam, The Netherlands
      date: 6-8th June
      spoken:
          - title: "Growing spiders to crawl the web"
            feedback: https://joind.in/talk/view/8462
            slides: http://www.slideshare.net/juokaz/growing-spiders-to-crawl-the-web-dutch-php-conference
    - title: Symfony Live Portland conference
      location: Portland, OR, USA
      date: 20-24th May
      spoken:
          - title: "Process any amount of data. Any time"
            feedback: http://joind.in/talk/view/8664
            slides: http://www.slideshare.net/juokaz/process-any-amount-of-data-any-time-symfony-live
    - title: phpDay conference
      location: Verona, Italy
      date: 17-18th May
      spoken:
          - title: "Building distributed systems"
            feedback: http://joind.in/talk/view/8648
            slides: http://www.slideshare.net/juokaz/building-distributed-systems-phpday-2013
    - title: Future Insights Live
      location: Las Vegas, NV, USA
      date: 29th April - 2nd May
      spoken:
          - title: "Throw some data science at it"
            slides: http://www.slideshare.net/juokaz/throw-some-data-science-at-it-future-insights-live
    - title: Web conference, part of InfoShow
      location: Kaunas, Lithuania
      date: 20th April
      spoken:
          - title: "How not to get fired"
    - title: Whisky Web II conference
      location: Edinburgh, UK
      date: 12-13th April
      info: Organised my second conference and delivered the opening keynote
    - title: Melbourne PHP user group
      location: Melbourne, Australia
      date: 19th March
      spoken:
          - title: "You Can't Optimize What You Can't Measure"
            slides: http://www.slideshare.net/juokaz/you-cant-optimize-what-you-cannot-measure-php-uk
    - title: Sydney PHP user group
      location: Sydney, Australia
      date: 28th February
      spoken:
          - title: "REST. Let's get the facts straight"
            slides: http://www.slideshare.net/juokaz/rest-lets-get-the-facts-straight-fowa-london
    - title: PHP UK conference
      location: London, UK
      date: 22-23th February
      spoken:
          - title: "You Can't Optimize What You Can't Measure"
            slides: http://www.slideshare.net/juokaz/you-cant-optimize-what-you-cannot-measure-php-uk
            feedback: http://joind.in/talk/view/8056
    - title: SunshinePHP conference
      location: Miami, FL, USA
      date: 8-9th February
      spoken:
          - title: "Virtualized Development"
            slides: http://www.slideshare.net/juokaz/virtualized-development-sunshine-php
            feedback: http://joind.in/talk/view/8018
    - title: PHPBenelux conference
      location: Antwerp, Belgium
      date: 25-26th January
      spoken:
          - title: "Process any amounts of data. Any time"
            slides: http://www.slideshare.net/juokaz/process-any-amounts-of-data-any-time-php-benelux-2013
            feedback: http://joind.in/talk/view/7801
  - year: 2012
    talks:
    - title: Future of Web Apps
      location: Prague, Czech Republic
      date: 27-29th November
      spoken:
          - title: "The only PHP framework you'll need: Symfony2"
            slides: http://www.slideshare.net/juokaz/the-only-php-framework-youll-need-symfony2-fowa-prague
    - title: Future of Web Apps
      location: London, UK
      date: 15-17th October
      spoken:
          - title: "REST. Let's get the facts straight"
            slides: http://www.slideshare.net/juokaz/rest-lets-get-the-facts-straight-fowa-london
            feedback: http://joind.in/talk/view/7474
    - title: New York City PHP user group
      location: New York, NY, USA
      date: 1st October
      spoken:
          - title: "Introduction to Symfony2"
            slides: http://www.slideshare.net/juokaz/introduction-to-symfony2-nyphp
    - title: REST Fest
      location: Greenville, SC, USA
      date: 13-15th September
      spoken:
          - title: "RESTful Open Data"
            slides: http://www.slideshare.net/juokaz/restful-opendata
    - title: Funconf
      location: Dublin, Ireland
      date: 31st August - 2st September
    - title: Sheffield PHP User Group
      location: Sheffield, UK
      date: 13th June
      spoken:
          - title: "REST: The bar fight"
    - title: Login conference
      location: Vilnius, Lithuania
      date: 31st May - 1st June
      spoken:
          - title: Open Data
            slides: http://www.slideshare.net/juokaz/open-data-login-conference
    - title: DrupalCamp Scotland
      location: Edinburgh, UK
      date: 25-26th May
      spoken:
          - title: "Symfony: An Introduction"
    - title: phpDay conference
      location: Verona, Italy
      date: 18-19th May
      spoken:
          - title: "Lazy Evaluation: stop wasting memory and time"
            slides: http://www.slideshare.net/juokaz/lazy-evaluation-stop-wasting-memory-and-time-phpday
            feedback: http://joind.in/talk/view/6378
    - title: 4Developers conference
      location: Poznań, Poland
      date: 17-18th April
      spoken:
          - title: Choosing The Right NoSQL Database
            slides: http://www.slideshare.net/juokaz/choosing-the-right-nosql-database-4developers
            feedback: http://joind.in/talk/view/6325
    - title: RESTful Design workshop, part of World Wide Web conference
      location: Lyon, France
      date: 17th April
    - title: Whisky Web conference
      location: Edinburgh, UK
      date: 13-14th April
      info: Organised my first conference and delivered the opening keynote
    - title: ConFoo conference
      location: Montreal, Canada
      date: 29th February - 2nd March
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2-confoo
            feedback: http://joind.in/talk/view/6109
          - title: RESTful Web Services with Python
            slides: http://www.slideshare.net/juokaz/restful-web-services-with-python-confoo
            feedback: http://joind.in/talk/view/5994
    - title: PHP UK conference
      location: London, UK
      date: 24-25th February
    - title: PHPBenelux conference
      location: Antwerp, Belgium
      date: 27-28th January
      spoken:
          - title: "Doctrine 2: An Introduction"
            slides: http://www.slideshare.net/juokaz/doctrine-2-an-introduction-php-benelux
            feedback: https://joind.in/talk/view/4773
  - year: 2011
    talks:
    - title: PHPDays, part of OSIDays conference
      location: Bangalore, India
      date: 20-21th Nov
      spoken:
          - title: Doctrine 2
            workshop: yes
          - title: The new era of PHP frameworks
    - title: PHP Barcelona conference
      location: Barcelona, Spain
      date: 28-29th October
      spoken:
          - title: PHP in the Cloud
            slides: http://www.slideshare.net/juokaz/php-in-the-cloud-php-barcelona
            feedback: http://joind.in/talk/view/4317
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2-php-barcelona
            feedback: http://joind.in/talk/view/4311
    - title: ZendCon conference
      location: Santa Clara, CA, USA
      date: 17-20th October
      spoken:
          - title: Doctrine 2
            workshop: yes
            feedback: http://joind.in/talk/view/3755
    - title: PHPNW conference
      location: Manchester, United Kingdom
      date: 8-9th October
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2-phpnw11
            feedback: http://joind.in/talk/view/3587
    - title: Azure All Access conference
      location: Dublin, Ireland
      date: 6-7th October
      info: Attended to showcase and discuss Azure and PHP integration and developments,
    - title: Edinburgh PHP user group
      location: Edinburgh, UK
      date: 28th September
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2-edinburgh-php-meetup
    - title: PFCongress conference
      location: Utrecht, The Netherlands
      date: 17th September
      spoken:
          - title: The new era of PHP frameworks
            slides: http://www.slideshare.net/juokaz/the-new-era-of-php-frameworks-pfcongres
            feedback: http://joind.in/talk/view/3656
    - title: Dynamic Languages conference
      location: Edinburgh, UK
      date: 29th August
      spoken:
          - title: ‎RESTful Web Services with Python
            slides: http://www.slideshare.net/juokaz/restful-web-services-with-python-dynamic-languages-conference
            feedback:
    - title: PHP North East user group
      location: Newcastle upon Tyne, UK
      date: 19th July
      spoken:
          - title: What is Doctrine ORM and should I use it?
            slides: http://www.slideshare.net/juokaz/what-is-doctrine-orm-and-should-i-use-it-phpne
    - title: JumpInCamp!
      location: Seattle, WA, USA
      date: 19-24th June
      info: Invited by Microsoft to help various PHP projects improve support for Windows, SQL Server and Azure
    - title: Dutch PHP conference
      location: Amsterdam, The Netherlands
      date: 19-21th May
      spoken:
          - title: Doctrine 2
            workshop: yes
            slides:
            feedback: http://joind.in/talk/view/3213
          - title: The new era of PHP frameworks
            slides: http://www.slideshare.net/juokaz/the-new-era-of-php-frameworks-dpc
            feedback: http://joind.in/talk/view/3244
    - title: phpDay conference
      location: Verona, Italy
      date: 12-14th May
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2-phpday-italy
            feedback: http://joind.in/talk/view/2990
          - title: Optimizing Zend Framework
            slides: http://www.slideshare.net/juokaz/optimizing-zend-framework-phpday-italy-7962825
            feedback: http://joind.in/talk/view/3020
    - title: Web conference, part of InfoShow
      location: Kaunas, Lithuania
      date: 9th April
      spoken:
          - title: Plaktuko problema
            slides: http://www.slideshare.net/juokaz/plaktuko-problema
            feedback:
    - title: 4Developers conference
      location: Warsaw, Poland
      date: 4th April
      spoken:
          - title: "Zend Framework 2.0: Let’s Rock!"
            slides: http://www.slideshare.net/juokaz/zend-framework-20-lets-rock
            feedback: http://joind.in/talk/view/3202
    - title: DrupalCamp Lisboa
      location: Lisbon, Portugal
      date: 26th March
      spoken:
          - title: Drupal and Windows?! Yes
            slides: http://www.slideshare.net/juokaz/drupal-and-windows-yes
            feedback:
    - title: PHP UK conference
      location: London, UK
      date: 25th February
  - year: 2010
    talks:
    - title: JumpInCamp!
      location: Seattle, WA, USA
      date: 16-19th November
      info: Invited by Microsoft to work on Doctrine 2 SQL Server support
    - title: Forum PHP
      location: Paris, France
      date: 9-10th November
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-20-forum-php
            feedback: http://joind.in/talk/view/2105
    - title: Microsoft /web day
      location: Vilnius, Lithuania
      date: 5th November
      spoken:
          - title: PHP on Windows
            slides: http://www.slideshare.net/juokaz/php-on-windows-web-day
    - title: PHP Barcelona conference
      location: Barcelona, Spain
      date: 29-30th October
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/2010-1029doctrine-2pbc10-5607358
    - title: PHPNW conference
      location: Manchester, UK
      date: 9-10th October
      spoken:
          - title: Optimizing Zend Framework
            slides: http://www.slideshare.net/juokaz/optimizing-zend-framework
            feedback: http://joind.in/talk/view/2060
    - title: Dutch PHP conference
      location: Amsterdam, The Netherlands
      date: 10-12th June
      spoken:
          - title: Doctrine 2
            slides: http://www.slideshare.net/juokaz/doctrine-2
            feedback: http://joind.in/talk/view/1769
    - title: PHP North West user group
      location: Manchester, UK
      date: 1st June
      spoken:
          - title: Practical ORMs
            slides: http://www.slideshare.net/juokaz/practical-orms
    - title: phpDay conference
      location: Corropoli, Italy
      date: 12-14th May
      spoken:
          - title: Practical ORMs
            workshop: yes
            feedback: http://joind.in/talk/view/1444
    - title: Lithuanian PHP conference
      location: Kaunas, Lithuania
      date: 24th April
      spoken:
          - title: Būk žingsniu priekyje!
            slides: http://www.slideshare.net/juokaz/bk-ingsniu-priekyje
      info: First talk in a PHP conference
    - title: JumpInCamp!
      location: Zurich, Switzerland
      date: 6-10th April
    - title: Microsoft MIX10
      location: Las Vegas, NV, USA
      date: 15-17th March
    - title: PHP UK conference
      location: London, UK
      date: 26th February
  - year: 2009
    talks:
    - title: PHPNW conference
      location: Manchester, UK
      date: 10-11th October
      info: Attended first ever PHP conference
